In [3]:
import numpy as np

In [2]:
random_array_4=np.random.randint(10,size=(5,3))

In [3]:
random_array_4

array([[9, 7, 4],
       [9, 4, 2],
       [6, 7, 2],
       [3, 6, 8],
       [3, 4, 6]])

In [4]:
np.unique(random_array_4)

array([2, 3, 4, 6, 7, 8, 9])

In [4]:
a1=np.array([1,2,3])

In [18]:
a2=np.array([[1,2.0,3.3],
            [4,5,6.5]])

In [22]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [8]:
a1[0]

1

In [9]:
a2[0]

array([1. , 2. , 3.3])

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a2[1]

array([4. , 5. , 6.5])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [18]:
a4=np.random.randint(10, size=(2,3,4,5))

In [19]:
a4

array([[[[8, 4, 4, 5, 6],
         [4, 0, 4, 0, 5],
         [0, 0, 5, 5, 6],
         [5, 1, 4, 8, 2]],

        [[2, 5, 8, 1, 9],
         [0, 6, 7, 0, 1],
         [0, 4, 2, 6, 9],
         [7, 2, 6, 8, 1]],

        [[2, 2, 8, 6, 6],
         [8, 2, 8, 8, 5],
         [2, 1, 9, 8, 6],
         [0, 4, 8, 2, 9]]],


       [[[2, 6, 8, 2, 9],
         [4, 0, 2, 3, 1],
         [4, 8, 4, 3, 1],
         [9, 9, 4, 8, 5]],

        [[7, 6, 4, 9, 2],
         [3, 9, 5, 6, 9],
         [9, 5, 9, 4, 1],
         [3, 8, 6, 4, 3]],

        [[2, 3, 6, 9, 0],
         [4, 2, 5, 3, 4],
         [7, 1, 4, 8, 0],
         [5, 9, 9, 8, 4]]]])

In [20]:
a4.shape

(2, 3, 4, 5)

In [21]:
a4.ndim

4

In [22]:
a4

array([[[[8, 4, 4, 5, 6],
         [4, 0, 4, 0, 5],
         [0, 0, 5, 5, 6],
         [5, 1, 4, 8, 2]],

        [[2, 5, 8, 1, 9],
         [0, 6, 7, 0, 1],
         [0, 4, 2, 6, 9],
         [7, 2, 6, 8, 1]],

        [[2, 2, 8, 6, 6],
         [8, 2, 8, 8, 5],
         [2, 1, 9, 8, 6],
         [0, 4, 8, 2, 9]]],


       [[[2, 6, 8, 2, 9],
         [4, 0, 2, 3, 1],
         [4, 8, 4, 3, 1],
         [9, 9, 4, 8, 5]],

        [[7, 6, 4, 9, 2],
         [3, 9, 5, 6, 9],
         [9, 5, 9, 4, 1],
         [3, 8, 6, 4, 3]],

        [[2, 3, 6, 9, 0],
         [4, 2, 5, 3, 4],
         [7, 1, 4, 8, 0],
         [5, 9, 9, 8, 4]]]])

In [23]:
a4[:, :, :, :4]

array([[[[8, 4, 4, 5],
         [4, 0, 4, 0],
         [0, 0, 5, 5],
         [5, 1, 4, 8]],

        [[2, 5, 8, 1],
         [0, 6, 7, 0],
         [0, 4, 2, 6],
         [7, 2, 6, 8]],

        [[2, 2, 8, 6],
         [8, 2, 8, 8],
         [2, 1, 9, 8],
         [0, 4, 8, 2]]],


       [[[2, 6, 8, 2],
         [4, 0, 2, 3],
         [4, 8, 4, 3],
         [9, 9, 4, 8]],

        [[7, 6, 4, 9],
         [3, 9, 5, 6],
         [9, 5, 9, 4],
         [3, 8, 6, 4]],

        [[2, 3, 6, 9],
         [4, 2, 5, 3],
         [7, 1, 4, 8],
         [5, 9, 9, 8]]]])

In [24]:
a4[:, :, :, :2]

array([[[[8, 4],
         [4, 0],
         [0, 0],
         [5, 1]],

        [[2, 5],
         [0, 6],
         [0, 4],
         [7, 2]],

        [[2, 2],
         [8, 2],
         [2, 1],
         [0, 4]]],


       [[[2, 6],
         [4, 0],
         [4, 8],
         [9, 9]],

        [[7, 6],
         [3, 9],
         [9, 5],
         [3, 8]],

        [[2, 3],
         [4, 2],
         [7, 1],
         [5, 9]]]])

In [25]:
a4[:, :, :, :3]

array([[[[8, 4, 4],
         [4, 0, 4],
         [0, 0, 5],
         [5, 1, 4]],

        [[2, 5, 8],
         [0, 6, 7],
         [0, 4, 2],
         [7, 2, 6]],

        [[2, 2, 8],
         [8, 2, 8],
         [2, 1, 9],
         [0, 4, 8]]],


       [[[2, 6, 8],
         [4, 0, 2],
         [4, 8, 4],
         [9, 9, 4]],

        [[7, 6, 4],
         [3, 9, 5],
         [9, 5, 9],
         [3, 8, 6]],

        [[2, 3, 6],
         [4, 2, 5],
         [7, 1, 4],
         [5, 9, 9]]]])

In [26]:
a4[:, :, :, :1]

array([[[[8],
         [4],
         [0],
         [5]],

        [[2],
         [0],
         [0],
         [7]],

        [[2],
         [8],
         [2],
         [0]]],


       [[[2],
         [4],
         [4],
         [9]],

        [[7],
         [3],
         [9],
         [3]],

        [[2],
         [4],
         [7],
         [5]]]])

In [5]:
a1

array([1, 2, 3])

In [10]:
ones=np.ones((1,3))

In [11]:
ones

array([[1., 1., 1.]])

In [12]:
ones=np.ones(3)

In [13]:
ones

array([1., 1., 1.])

In [14]:
a1+ones

array([2., 3., 4.])

In [15]:
a1-ones

array([0., 1., 2.])

In [16]:
a1*ones

array([1., 2., 3.])

In [21]:
a1

array([1, 2, 3])

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [23]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [26]:
a1/ones

array([1., 2., 3.])

In [28]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [27]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [31]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [33]:
a1+ones

array([2., 3., 4.])

In [32]:
np.add(a1,ones)

array([2., 3., 4.])

In [34]:
a1%2

array([1, 0, 1], dtype=int32)

In [35]:
a1/2

array([0.5, 1. , 1.5])

In [36]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [37]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [38]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [39]:
listy_list=[1,2,3]

In [40]:
type(listy_list)

list

In [41]:
sum(listy_list)

6

In [42]:
a1

array([1, 2, 3])

In [43]:
type(a1)

numpy.ndarray

In [44]:
sum(a1)

6

In [45]:
np.sum(a1)

6

In [46]:
massive_array=np.random.random(100000)

In [47]:
massive_array.size

100000

In [49]:
massive_array[:10]

array([0.29210427, 0.33448265, 0.71548331, 0.93828514, 0.5307973 ,
       0.90371713, 0.54595682, 0.68724049, 0.61409726, 0.06217189])

In [50]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

13.4 ms ± 663 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
99.3 µs ± 2.39 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [51]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [52]:
np.mean(a2)

3.6333333333333333

In [53]:
np.max(a2)

6.5

In [54]:
np.min(a2)

1.0

In [55]:
np.std(a2)

1.8226964152656422

In [56]:
np.var(a2)

3.3222222222222224

In [57]:
np.sqrt(np.var(a2))

1.8226964152656422